import random
import datetime
import html

# --- TEXTES PAR VOIX ---

blake = [
"le dispositif organise une séparation fonctionnelle entre perception et identification",
"l’image dépend d’un point de vue qui ne peut pas s’y intégrer",
"le fond diffus empêche toute stabilisation réflexive de l’image",
"le système fonctionne sans produire de retour exploitable sur l’observateur",
"l’absence du corps empêche toute validation du point de vue",
"le dispositif introduit une dissymétrie entre vision et présence",
"les paramètres perceptifs cessent d’être constants dans ce système",
"le dispositif fonctionne. c’est déjà beaucoup",
"le système génère une image indépendante de toute validation subjective",
"le dispositif ne permet aucune position depuis laquelle l’image pourrait être saisie comme objet",
"l’image ne permet aucune appropriation du point de vue",
"le dispositif stabilise une absence comme condition de visibilité",
"le système empêche toute correspondance directe entre regard et image",
"le dispositif maintient une tension constante entre présence et absence",
"l’image persiste sans se référer à une origine subjective",
"le système rend toute identification instable sans la supprimer",
"aucune position d’observation ne reste suffisamment stable pour devenir un point de référence",
"l’image se maintient sans jamais intégrer celui qui la perçoit",
"la structure empêche toute coïncidence entre regard et représentation",
"percevoir revient ici à traverser une organisation dont les limites restent invisibles",
"le dispositif configure une expérience où le sujet ne peut pas apparaître comme tel",
"l’image fonctionne sans jamais se stabiliser dans une forme définitive",
"le dispositif maintient une séparation opératoire entre ce qui est perçu et ce qui perçoit",
"la perception est contrainte par une organisation qui la dépasse",
"le cadre impose une organisation qui précède toute expérience perceptive",
"l’image maintient sa cohérence en excluant toute inscription du sujet",
"le système semble avoir oublié la question",
"le point de vue agit sur l’image sans jamais pouvoir y prendre place",
"le regard devient ici une fonction du dispositif plutôt qu’une propriété du sujet",
"tout est en place, sauf l’essentiel",
]

lei = [
"tu arrives... quand la position n’est déjà plus disponible",
"ce que tu vois se décide... avant ton regard",
"la netteté serait un contresens ici...",
"le retour a lieu... mais pas dans ta direction",
"ce n’est pas toi qui manques... c’est la place que tu crois occuper",
"tu regardes depuis un point déjà déplacé",
"le cadre a changé... sans que tu le voies",
"le système te précède désormais",
"ce que tu perçois se forme... ailleurs que là où tu te tiens",
"le point existe... mais il ne t’est jamais donné",
"tu vois... mais depuis un décalage irréductible",
"le cadre agit... avant que tu n’y entres",
"tu es pris dans ce qui ne te renvoie rien",
"l’absence est déjà là... avant ton regard",
"tu ne peux pas confirmer ce que tu vois",
"ce qui te dépasse agit déjà en toi...",
"la distance est déjà en place... avant ton geste",
"tu ne peux pas t’installer dans ce que tu vois",
"tu es déjà engagé... avant même de regarder",
"tu arrives après que quelque chose a déjà commencé à se décider",
"tu ne peux pas revenir sur ce qui est déjà là",
"le regard ne coïncide jamais avec ce qu’il voit",
"tu restes dehors... même en regardant",
"aucun point de départ ne t’est accessible",
"tu peux te reconnaître... sans jamais t’y fixer",
"la séparation reste... même quand tu t’en approches",
"tu es là... et déjà ailleurs",
"tu crois regarder quelque chose... mais ça continue ailleurs",
"ce que tu cherches ici a peut-être déjà changé de place",
"le retour existe... mais ne revient pas",
"tu étais là il y a une seconde...",
"attends... non",
]

sorel = [
"tu continues à parler de miroir, alors que rien ici ne remplit les conditions du reflet",
"la présence visible suppose la suppression de ce qui devrait la garantir",
"le flou n’est pas un défaut, c’est la condition même de ce qui apparaît",
"la circularité du regard est ici rendue structurellement impossible",
"le sujet n’est pas absent, il est rendu inopérant par le dispositif",
"la présence est produite au prix de son propre effacement",
"la stabilité apparente masque une transformation des conditions",
"il n’y a jamais eu de point extérieur à ce dispositif",
"la visibilité repose ici sur une exclusion constitutive du sujet",
"la transparence supposée est ici structurellement impossible",
"la structure précède ce que tu crois vivre immédiatement",
"la représentation suppose ici l’effacement de celui qui regarde",
"ce qui apparaît ne peut être séparé de ce qui lui fait défaut",
"il faudrait probablement recommencer... ou simplement recharger la page?",
"l’expérience dépend d’une extériorité irréductible",
"la proximité perceptive est une illusion produite",
"l’identification fonctionne comme une opération toujours incomplète",
"la résolution est empêchée par la condition même du dispositif",
"le dispositif interdit le retour exact vers la position qui l’a produit",
"l’origine est neutralisée par la logique du dispositif",
"toute apparition suppose ici qu’une partie de sa propre condition reste hors champ",
"la coïncidence est annulée par le fonctionnement du dispositif",
"nous avons perdu le fil, semble-t-il",
"la tension n’est pas un effet mais une condition",
"l’appropriation est neutralisée par la structure du dispositif",
"la forme excède toujours ce qu’elle prétend être",
"la condition de vision implique une perte préalable de présence",
"la critique ne trouve plus de point d’appui",
"la distinction ne disparaît pas ; elle cesse simplement de produire ses effets",
"le dispositif annule les distinctions qu’il semblait produire",
]

anaya = [
"ce qui apparaît t’inclut... sans jamais te contenir",
"tu es là... mais déjà pris dans ce qui t’échappe",
"la surface ne fixe rien... elle laisse passer",
"le cercle existe... mais il ne se referme pas sur toi",
"tu touches à ce qui t’échappe sans pouvoir le retenir",
"la position devient un passage que tu ne peux pas fixer",
"tout reste... mais autrement",
"tu fais déjà partie de ce qui te dépasse",
"tu es là, mais déjà déplacé dans ce qui apparaît",
"ce que tu perds te relie autrement",
"la distance ne sépare pas... elle transforme",
"ce qui précède te porte sans se montrer",
"ce qui t’accueille ne demande pas que tu sois visible",
"ce qui manque ouvre un passage",
"tu continues pourtant à être là",
"tu participes à ce qui te traverse",
"ce qui semble proche est déjà ailleurs",
"tu passes... sans pouvoir retenir",
"tu habites cette distance",
"tu es présent... autrement que visible",
"ce dehors t’habite déjà",
"tout commence... sans commencer",
"tu es en mouvement dans ce qui te définit",
"tu es séparé... sans être isolé",
"les deux coexistent sans se résoudre",
"tu avances dans ce qui ne revient pas",
"tout continue... sans fin stable",
"la surface relie sans jamais fixer",
"tu arrives dans quelque chose qui était déjà en train de devenir",
"ce qui apparaît ne demande rien et pourtant te traverse",
"nous y étions presque",
"peut-être que c’était déjà fini",
]

# 30 phrases par voix : 9 anciennes formulations remplacées par 9 nouvelles.
# La mécanique de génération est volontairement laissée à l’étape suivante.
